kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: cd-pipeline
  namespace: ctfoci-dev
  uid: faef4aa3-f5c0-4f57-967c-1ddf2c501998
  resourceVersion: '2792182664'
  creationTimestamp: '2024-12-03T22:22:22Z'
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: cd-listener
  annotations:
    openshift.io/host.generated: 'true'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2024-12-03T22:22:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/part-of': {}
            'f:eventlistener': {}
        'f:spec':
          'f:port':
            .: {}
            'f:targetPort': {}
          'f:tls':
            .: {}
            'f:termination': {}
          'f:to':
            'f:kind': {}
            'f:name': {}
            'f:weight': {}
          'f:wildcardPolicy': {}
    - manager: openshift-router
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2024-12-03T22:22:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:ingress': {}
      subresource: status
spec:
  host: cd-pipeline-ctfoci-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com
  to:
    kind: Service
    name: el-cd-listener
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
  wildcardPolicy: None
status:
  ingress:
    - host: cd-pipeline-ctfoci-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2024-12-03T22:22:22Z'
      wildcardPolicy: None
      routerCanonicalHostname: router-default.apps.sandbox-m4.g2pi.p1.openshiftapps.com
